/*
 * This source file was generated by the Gradle 'init' task
 */
package nl.thomasgoossen;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GlServerTest {

}
